document.addEventListener('DOMContentLoaded', () => {
    const messagesContainer = document.getElementById('messages');
    const modal = document.getElementById('messageModal');
    const fullMessage = document.getElementById('fullMessage');
    const closeBtn = document.getElementsByClassName('close')[0];

    // Custom messages for each box
    const messages = [
        "Your religious values. Even just having the discussion the other day, seeing you ground your decision making and morals in Islam was not only inspiring but attractive. It's the most important thing for me in a partner, and not only does your character completely reflect it, but your actions of being so connected to the Masjid and the Quran is amazing. It has helped secure my brain in knowing that I have a partner moving forward that actually can complete half my deen, because you'll only remind me of it and continue to improve both myself and our children in that aspect.",
        "Your mind. You're extremely intelligent, resourceful, and effective. You get good grades, know how to finesse a system, and mA work amazing internhsips and iA a great full time job where you make more money than even me. Your ideas at ASO meetings were always so bright and intuitive, and you were by far the most helpful person to the club in terms of event organizing, execution, and chipping in where others fell short. You're going to be the most helpful wife and mom ever, considering I love to live life on fast mode and have a bajillion things going on for myself, and for our kids.",
        "Your ambition. Truly one of the things that has made me fall the hardest for you. You're always looking to improve yourself, whether that is: Physically in the gym/on runs/your gym class that killed you, Mentally: Always wanting to learn new things and expand your horizons, taking on a difficult major and career path, or Financially: Working all these jobs, buying your own car, investing and side hustles. I've never met a woman as ambitious as you, and not only does it inspire me, but it makes me so happy to know I'm going to have a partner and teammate that will push me and the family I create with her to new heights.",
        "Your family. As much as some of them may dislike me (LOL rawr xD) one thing that I love about you is you come from a great family. Mashallah, your father is very wise, religious, and has sound morals, I can tell where you get yours from. He's an amazingly established man, and he has my full respect, not only by being at the masjid everyday at Fajr and Isha and carrying the youth, but by also simultaneously being so successful in his own career as a civil engineer. It's exactly how I want to be. Of course, your mother has done a fantastic job of raising 5 amazing children, all of whom will have great success iA. Your older brother is a successful computer scientist, your sister is a lawyer, your other sister is in PA school, your other sisters ... (idrk anything about them but Maiyar was chill from what I remember LOL (wish I could code emojis heh)), and you have a future soccer superstar in Jibreel. I feel like I would fit in very well, and they carry great respect and honor. Perfect in law family example for my kids.",
        "Your supportiveness. You do this so well with your friends, where you're always trying to help them out in any way you can, even as so simple as just hyping them up and putting a smile on their face. I feel it 10x more. You're always so excited whenever I do something good, which makes me feel 100x better about myself. You're always there for me when things go wrong (after laughing at my sadness for a little bit of course xD), and it makes me feel like I can get back from anything. You always celebrate with me and cheer me up. As life continues to throw things my way, there's literally not a single person in this world who I can imagine having by my side other than you. I'm invincible and undefeated so long as you're by my side :)",
        "Your excitedness. Man, one thing that I absolutely love and adore about you is your energy. I love when you're so bubbly. I love when you jump around and squeal. I love when you clap your hands, and meow, and say YIPPIE, and anything else. I love how lighthearted you are, how sarcastic you are. You brighten uo every room you're in. I love how you dance after every time you score in pickleball or in soccer. You radiate such amazing vibes, it makes me feel so warm. I love love love how goofy you are. It makes me feel so comfortable, and I can always be my true self around you. I love how autistic you are, and I wish you showed me that side as much as you show the girls. It's one of my favorites of your 27 personalities. I don't think I can ever have a dull moment with you.",
        "Your kindness. You always try to include people. You always try to give them the benefit of the doubt. You always try to help them with whatever they ask, even if you yourself lack knowledge of it. You greet people with a smile, carry conversations with them, and make sure they feel valued and listened to. You're always there for your friends, giving them great advice, and trying to guide them as best as you can. People are drawn towards you. I've noticed it. Everyone enjoys having you around. Especially me the most. You always make me feel heard, loved, and assured. You wear your personality on your sleeve and it's great.",
        "Your humility. Batoul, you are the finest woman to ever walk the face of the Earth. I mean it. You have literally everything a guy could ever dream of. You are everything a girl could ever want to be. Yet, even with all that, you are the most humble person I know. It could be soooo easy for you to have a big head and an ego. For you to treat people as not as important, or not worth your time. But you don't. You treat everyone equally, and give them all the time of day. You don't have an arrogant, conceited superiority complex that a lot of people who are blessed with half of what you have tend to portray. It's so fascinating to me, but again, it's just a testament to your character. It's sooooo attractive.",
        "Your humor. Batoul. You are the funniest woman I've ever met. You have me grinning from ear to ear like an idiot whenever I'm around you, calling you, or even texting you. You roast me, which is so fun. You're sarcastic, creative, and your mannerisms are hilarious. You match my energy so perfectly. Our flirt to roast ratio is perfect, but even outside of that, the way you interact with myself and others always has me laughing in a good way. You're the funniest person in groupchats too. Literally one of my favorite things about you, I can't wait to laugh the rest of my amazing life away with you.",
        "Your confidence. I know I usually say this as an insult instead of a compliment, but this time I actually mean it lol. You are extremely social and confident. It makes being in public with you 100x more fun. Remember when we did the siblings or dating thing with those random kids at Bond Park? That's only possible because, like me, you have extreme confidence in public and around strangers. It makes me so much more excited to have adventures with you, because you'll be down to do so much more stuff with me. You entertain any room, and are able to create connections (both personal and professional) like no other. I love that about you so much.",
        "Your athleticism. My oh myyyyyyyyyyyy this thing gets me going when it comes to you. As an athlete myself, it has always been my DREAM to do physical activities with my wife. I love nature, hiking, doing stuff that's off the normal trails/paths that require a little bit of physical abilities, sports, everything. I can only imagine how fun doing spontaneuous outdoor stuff will be with you. I LOVE THAT YOU PLAY SOCCER WITH ME. I love that you play pickleball with me. I love how I can do the things that I enjoy the most, alongside the woman that I enjoy being around the most. It makes both the activity, and you, 100x sweeter and more exciting to me. I can't wait to stay in physical shape with you, and raise some crazy freakish athlete kids with you.",
        "Your willingness to do things that I like. Whenever I want to do something, you're always down to try it. You know how much it means to me, and with a smile on your face you always willingly tag along. It makes it so much easier for me to plan things with you, and we're always able to open up new avenues and fond memories of activities that we do together. It can never be mundane with you. I will always have the perfect woman by my side, making my life a gazillion times more fun.",
        "Your spontaneity. Oh my god I love you. I love that you're so spontaneous. Since I'm geared the exact same way. I can tell you to do something with me in the next minute and you're down. I can tell you to go somehwere with me and you're down. Even when we're going somewhere or doing something, I love how we always get distracted and go on these extra sidequests that are NEVER planned. Like the hotel where we just talked in the lobby for hours. I also love how this is true in our conversations. We always get distracted, and 20 minutes later we realize we haven't even talked about what we wanted to. Life is a blur with you. You make every moment fun, and it's always something new. I'm so so so excited to travel the world with you. I'm super spontaneous when I travel, and I just know you're so down for everything. You're my perfect partner literally.",
        "Your class. You are an extremely classy woman. You have such sophistication and refinery, it's like I'm walking around with the rarest ruby on the Earth. You speak with elegance, you walk with grace, Batoul I'm literally in awe of you whenever I'm around you. People love talking to you and you can connect with highly educated folk. When I walk around with you, I'm so proud to be there. You carry yourself with dignity through the issues that come up in your life. I love how you've dealt with all these dumb rumors about you. You were firm and assertive yet respectful and classy. I can't wait to be able to claim you as mine. I'd tell the whole world, and walk around with a beam on my face and a sense of pride considering you're mine.",
        "Your style. I mean, I'm sure you know this already, but I want to just reaffirm it. You have fantastic style. You look good in literally everything I see you in. I've never met a woman who literally sparkles in every single color she wears. People think colors make things beautiful, but to me, you make colors beautiful. It's like I've known and seen colors in my life, but when you're around, you make the colors shine just a little extra. Not only can you dress well, but you can dress others well. Obviously, every piece of Karam looks so magnificent. That's why you sold out so quick. But it all looks amazing. Plus, your style notes for me are great as well. I know I'm gonna look good in everything, and I can't wait for you to dress me up everyday, and do my shopping for me so we can step out and be the hot couple that can dress well.",
        "Your ability to make me feel like a man. I love that you feel like you can rely on me. I love that you let me plan things, and just turn your brain off and let me guide you around. I love that you let me make decisions, and that you trust me when I do. I love that you listen to my advice. I love that you come to me with your problems and let me help you. I love that you let me do your coding and math problems. I love that you make me feel so smart and strong. I love that you support me through all thr things I'm doing. I love being a man for you. I can't wait to be your perfect husband, and just allow you to be the most feminine version of yourself you want to be.",
        "Your trust. I love that you trust me. I love how you're so willing to always hear me out. I love that you come to me for advice, and when I give it to you, you accept it. I love that if we ever disagree, you listen to me and are willing to change your mind instead of just trying to prove that you're right. I love that you confide everything to me. It makes me feel so valued. It makes me feel like a leader. It makes me feel like not only your man, but your best friend. Actually, I'm going to write a whole other box on this. But yeah, I love the idea that moving forward, I can be comfortable in making big decisions for us and you will support and trust me 100% along the way, and if I'm confused, you'll help guide me to the right way.",
        "Your beauty. I really could spend days and fill up entire websites on their own talking about this. I can never get enough of looking at you. Looking at you cools my eyes. Batoul, it physically is impossible to be more attractive than you are. Every single detail about you is so perfect, I'm fully convinced you're an angel on Earth. Your face is the most beautiful of Allah's creation. I look at sunsets, landscapes, cities, forrests, mountain, ANY nature view, and your face is still what brings my heart the most contentment. Looking at you makes my problems go away. You have the shiniest big bead chocolate eyes I know. I love seeing your pupils dilate when you look at me. Your skin is so fair, is the perfect shade, and is so soft to the touch. Your nose sits so perfectly in the middle of your face, with the perfect length, width, and shape. I love your comma nostrils. You have such thick, rich, and long eyelashes/eyebrows. It's such a lethal combo with your eyes it's not even fair. Your lips are so soft and rosy. The way they sit naturally, and the way they look when you smile is majestic. Your teeth are so white and clean, it feels like I'm literally looking at a set of pearls. When you smile, my heart stops. When I'm away from you, sometimes I look into the stars for comfort, and realize that you shine brighter than all of them combined. Your smile lines and dimples make my heart melt. Your cheek bones and jaw are so sharp and defined, you literally have the perfect structure. You're literally perfect. Everything about you. I can't find the words to actually measure how beautiful you are. You're the kind of girls people write songs about, and every love poem I read reminds me of you. You make me feel so lucky to even know you. And my GOD, you're the most beautiful thing ever naturally and with makeup. The thought of waking up next to you every single morning and knowing you're going to start my day off with looking at something so perfect is so exciting. Every moment of my life, no matter how old we get, is going to be me drooling over you. In bed, when we glam up for events, out the shower, everything. You are perfect. Your beauty is perfection. I wish I could write on and on and on, and learn better english words to describe it. I love your beauty.",
        "Your ability to love me. Batoul, you make me feel like the most special man in the world. You love me so perfectly in every single facet that love can be. Your words of affirmation are liquid gold to my ears. Everytime you give me a compliment, I get just as excited and happy as if I heard it the first time. You make me feel so damn handsome, you know that? And that gives me so much value. Your touch is out of this world. I love how much you always want to hold my hand, grab my arm, play with my hair (even though you ruin it xD), kiss my face and neck and body, run your hands over my chest abs and back, hug me, and just nuzzle your face as deep into my neck as you can. I love how tight you hold me. I love feeling your soft skin against mine, and especially against my lips. I love when I was just laying down on my stomach and you just rested your face on my back and ran your hands over it. I love how you text me long paragraphs. I love how you're always so excited when you're on facetime with me, or how you call me just because you miss my voice. I love how you planned such a cute painting date for me. Every single detail was so cute, from the blankets and pillows, to the mugs and different size paintbrushes as well as different paint colors, from the snacks and drinks, everything. You made me feel like a king. You make me feel like a king every single day. You love me in a way that makes my soul feel whole. You give the word love meaning that I didn't even know it could have. You are my first and last love, and I want to experience it all with you. The dunya is enjoyment, and the best of enjoyment is a righteous wife (hadith). You are my enjoyment Batoul, my love, my everything.",
        "Your ability to let me love you. I'm a very passionate, obsessive, freaky, clingy guy. I've heard countless stories online, and seen a plethora of experiences in person from my friends, where the guy loves too hard, and the girl does them do dirty. I've always been kind of afraid to love. I knew that I fit that category of man, where I love extremely hard, and was kinda terrified of somehow counter intuitively pushing away the woman of my dreams. Although you did push and pull with me a lot xD but for different reasons so I'll allow it. I was afraid that I would have to act differently in order to truly please and maintain a woman, that I couldn't be myself, which is a taxing thought. But Batoul, you are the easiest person to love in this world. It's so natural to love you. Every single form of love that I have, you enjoy. You love my passion for you. You love my obsessiveness for you. You love how possessive I am. You love how clingy and needy I am of you. And it makes loving you that much more sweet. I don't have to put a single guard up. I don't have to change my personality, my humor, or the amount of attention I give you. I don't have to play any games. Loving you is the easiest thing for me. I wake up everyday excited to love you. I live everyday happy to shower you with every ounce of love I have. Every bit of love I can offer, you take, and you reciprocate it back. Never in my life will I ever stop loving you, and never in my life will I ever stop showing you how much I love you. No matter how hard times get, loving you will always be easy, and you'll always feel my love. Our love will make the bad times feel like nothing, and the good times feel like everything. I love loving you.",
        "Above all, Batoul, I love the way you're my best friend. I love the way you're my soulmate. I love the way we match. I love how our personalities coincide. I love how our humor is the same. I love how we look similar. I love that you're the easiest person for me to talk to. I love that I tell you all my secrets. I love that I can be vulnerable with you. I love that I can roast you. I love that I can dance with you. I love expressing myself around you. Not only do I get to be so lucky to love you, I got even luckier to be so close to you. Our hearts reverberate together. Truthfully, there's no way we weren't created in a pair. You match my strengths and bring them out, and you match my flaws and hide them away. You make me the most excited man on the planet. I can't wait to marry you. If I could marry you in 5 minutes I would. I'd marry you in Raleigh, Cincinnati, Australia, Antarctica, on Mars, in front of all our friends and family, and in a cave with nobody but an Imam and a couple witnesses. Anything to be with you my love. I'm excited to embark on a journey with someone who has every positive attribute I can think of. Tell me, how does it feel to be able to make my life worth living?"
        // ...other messages
    ];

    // Create message boxes with "Read more" buttons
    messages.forEach(message => {
        const messageBox = document.createElement('div');
        const button = document.createElement('button');

        messageBox.classList.add('message-box');
        messageBox.innerText = message.substring(0, 100) + '...'; // Preview text
        button.innerText = 'Read more';
        
        // Show full message in modal on click
        button.addEventListener('click', () => {
            fullMessage.innerText = message; // Display full message
            modal.style.display = 'block'; // Show modal
        });

        messageBox.appendChild(button);
        messagesContainer.appendChild(messageBox);
    });

    // Close the modal when clicking the "x" button
    closeBtn.addEventListener('click', () => {
        modal.style.display = 'none'; // Hide modal
    });

    // Close the modal when clicking outside the modal content
    window.addEventListener('click', (event) => {
        if (event.target === modal) {
            modal.style.display = 'none'; // Hide modal
        }
    });
});
